export const restsArray = [
  {
    id: 0,
    title: 'Пицца плюс',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'image-01.jpg',
  },
  {
    id: 1,
    title: 'Тануки',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца и суши',
    image: 'image-02.jpg',
  },
  {
    id: 2,
    title: 'FoodBand',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'image-03.jpg',
  },
  {
    id: 3,
    title: 'Жадина-пицца',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Суши',
    image: 'image-04.jpg',
  },
  {
    id: 4,
    title: 'Точка еды',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'image-05.jpg',
  },
  {
    id: 5,
    title: 'PizzaBurger',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца и бургеры',
    image: 'image-06.jpg',
  },
];
